version: '3'

services:
  app:
    build: ./
    command: ['']
    environment:
      - NODE_ENV=${ENVIRONMENT:-development}
    volumes:
      - ./:/app:Z
    ports:
      - '4000:4000'
      - '9229'
    tty: true
    networks:
      - default

